# Generated by Django 2.0 on 2017-12-04 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20171203_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sublocality1',
            options={'ordering': ('name', 'locality')},
        ),
        migrations.AlterModelOptions(
            name='sublocality2',
            options={'ordering': ('parent', 'name')},
        ),
        migrations.AlterModelOptions(
            name='sublocality3',
            options={'ordering': ('parent', 'name')},
        ),
        migrations.AlterModelOptions(
            name='sublocality4',
            options={'ordering': ('parent', 'name')},
        ),
        migrations.AlterModelOptions(
            name='sublocality5',
            options={'ordering': ('parent', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='sublocality1',
            unique_together={('name', 'locality')},
        ),
        migrations.AlterUniqueTogether(
            name='sublocality2',
            unique_together={('name', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='sublocality3',
            unique_together={('name', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='sublocality4',
            unique_together={('name', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='sublocality5',
            unique_together={('name', 'parent')},
        ),
    ]
