# Generated by Django 2.0 on 2017-12-08 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20171204_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=165, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=165)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Locality')),
            ],
            options={
                'ordering': ('locality', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Country')),
            ],
            options={
                'ordering': ('country', 'code'),
            },
        ),
        migrations.CreateModel(
            name='PostalCodeSuffix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(max_length=15)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.PostalCode')),
            ],
            options={
                'ordering': ('code', 'suffix'),
            },
        ),
        migrations.AddField(
            model_name='address',
            name='colloquial_area',
            field=models.CharField(blank=True, default='', max_length=165),
        ),
        migrations.AddField(
            model_name='address',
            name='intersection',
            field=models.CharField(blank=True, default='', max_length=165),
        ),
        migrations.AddField(
            model_name='address',
            name='airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Airport'),
        ),
        migrations.AddField(
            model_name='address',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Neighborhood'),
        ),
        migrations.AlterUniqueTogether(
            name='postalcodesuffix',
            unique_together={('suffix', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='postalcode',
            unique_together={('code', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='neighborhood',
            unique_together={('name', 'locality')},
        ),
    ]
