# Generated by Django 2.0 on 2017-12-08 14:54
import re
from django.db import migrations

def move_postal(apps, schema_editor):
    # move postal code date from Locality model to PostalCode and
    # PostalCodeSuffix models
    Locality = apps.get_model('address', 'Locality')
    PostalCode = apps.get_model('address', 'PostalCode')
    PostalCodeSuffix = apps.get_model('address', 'PostalCodeSuffix')
    locs = Locality.objects.order_by('postal_code').distinct('postal_code')
    zip4 = re.compile(r'\d{5}-\d{4}')
    for loc in locs:
        if not loc.postal_code: continue # skip any missing postal code

        
        if loc.state.country.code == 'US' and zip4.match(loc.postal_code):
            # Postal is US zip+4, save suffix separately and link to code
            parts = loc.postal_code.split('-')
            code, code_new = PostalCode.objects.\
                         get_or_create(code=parts[0],
                                       country=loc.state.country)
            
            suff, suff_new = PostalCodeSuffix.objects.\
                             get_or_create(suffix=parts[1], code=code)

        else:
            code, code_new = PostalCode.objects.\
                             get_or_create(code=loc.postal_code,
                                           country=loc.state.country)

            
class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20171208_0331'),
    ]

    operations = [
        migrations.RunPython(move_postal),
    ]
