# Generated by Django 2.0 on 2017-12-09 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20171208_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='admin2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adm2_addresses', to='address.Admin2'),
        ),
        migrations.AddField(
            model_name='address',
            name='admin3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adm3_addresses', to='address.Admin3'),
        ),
        migrations.AddField(
            model_name='address',
            name='admin4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm4_addresses', to='address.Admin4'),
        ),
        migrations.AddField(
            model_name='address',
            name='admin5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm5_addresses', to='address.Admin5'),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc_addresses', to='address.PostalCode'),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code_suffix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcs_addresses', to='address.PostalCodeSuffix'),
        ),
        migrations.AddField(
            model_name='address',
            name='sublocality1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sl1_addresses', to='address.SubLocality1'),
        ),
        migrations.AddField(
            model_name='address',
            name='sublocality2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sl2_addresses', to='address.SubLocality2'),
        ),
        migrations.AddField(
            model_name='address',
            name='sublocality3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sl3_addresses', to='address.SubLocality3'),
        ),
        migrations.AddField(
            model_name='address',
            name='sublocality4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sl4_addresses', to='address.SubLocality4'),
        ),
        migrations.AddField(
            model_name='address',
            name='sublocality5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sl5_addresses', to='address.SubLocality1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='route',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='locality',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
    ]
