# Generated by Django 2.0 on 2017-12-09 16:42

from django.db import migrations

def move_sc(apps, schema_editor):
    """
    move state and country from locality to address
    """
    
    Address = apps.get_model('address', 'Address')
    for addr in Address.objects.all():
        if not addr.locality: continue
        addr.state = addr.locality.state
        addr.country = addr.locality.state.country
        addr.save()

        
class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_auto_20171209_1614'),
    ]

    operations = [
        migrations.RunPython(move_sc),
    ]
