# Generated by Django 2.0 on 2017-12-09 17:46

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_auto_20171209_1746'),
    ]

    operations = [
        # migrations.RunPython(dedupe),
        
        migrations.AlterUniqueTogether(
            name='locality',
            unique_together={('name', 'state')},
        ),
    ]
