# Generated by Django 2.0 on 2017-12-09 17:46

from django.db import migrations

def dedupe(apps, schema_editor):
    """
    remove duplicate localities
    """
    Address = apps.get_model('address', 'Address')
    Locality = apps.get_model('address', 'Locality')

    for addr in Address.objects.all():
        locs = Locality.objects.filter(name=addr.locality.name,
                                       state=addr.locality.state).\
                                       order_by(id)
        if len(locs) == 1: continue
        if addr.locality.id > locs[0].id:
            addr.locality = locs[0]
            addr.save()
        locs[1:].delete()

        
class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_auto_20171209_1746'),
    ]

    operations = [
        migrations.RunPython(dedupe),
        
        migrations.AlterUniqueTogether(
            name='locality',
            unique_together={('name', 'state')},
        ),
    ]
