# Generated by Django 2.0 on 2017-12-10 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0012_auto_20171209_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublocality1',
            name='admin2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Admin2'),
        ),
        migrations.AddField(
            model_name='sublocality1',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.State'),
        ),
        migrations.AlterField(
            model_name='sublocality1',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Locality'),
        ),
    ]
